### ISSUE TITLE
Dive starting time incorrect after combining

### ISSUE THREAD

**Issue by mdjong4** [sumoDave/GarminDiveFitAppender#2]
In the files that I combined all calculations are done correctly, only the dive starting time is incorrect. The code should take the 'oldest' time as start time. In the current version the start time is based on the second import file.

For example;
1.fit
Start time: 09:49
Duration: 14:54min

2.fit
Start time: 10:05
Duration: 13:29min

Results in Appended_1_2.fit
Start time: 10:05
Duration: 29:54min

**Comment by sumoDave** [comment]
The code specifically sorts the input files into chronological order, and sets the start time according to the first file. 
It was designed such that it didn't matter what order the files are specified as input arguments.

Is it possible to attach your original FIT files for me to investigate?

I can't reproduce with my files.

**Comment by mdjong4** [comment]
I am using these files.
[FIT files.zip](https://github.com/sumoDave/GarminDiveFitAppender/files/14979439/FIT.files.zip)

**Comment by sumoDave** [comment]
Initial start time was based on the first file's creation time. 
Mk2 differs from G1 in that the file creation time is at the completion of the activity, whereas the G1's file creation time is the start of activity.

Code fix applied.
