### ISSUE TITLE
Works with Descent Mk2i using a T2 transciever

### ISSUE THREAD

**Issue by bishop527** [sumoDave/GarminDiveFitAppender#8]
Not an issue, just wanted to let you know that I successfully used the tool to merge files from my Descent Mk2i that included data from a T2 transceiver. Did this for 2 different dives, first one with 2 FIT files, 2nd dive had 3 FIT files. I didn't do a bit by bit comparison of the merged data, but all the major fields appear to be correct and the trends of gas utilization look correct. Keep up the great work.

**Comment by sumoDave** [comment]
Glad it could help.
