### ISSUE TITLE
Any plans on releasing the source code?

### ISSUE THREAD

**Issue by hellozee** [sumoDave/GarminDiveFitAppender#9]
Hey, thanks for the utility, it works as expected with my Garmin mk3i too. I did try some stuff on my own to write something like this before arriving here but that didn't work out. I was wondering about the logic behind the tool. So would it be possible to share the source?

**Comment by sumoDave** [comment]
Glad my tool helped!

No plans to release source code. 

In terms of the logic behind it, I just followed the examples in the FIT SDK and the cookbook. 

The fit file format is message based protocol, so reading the data replays the messages as they were written, and writing a file is as simple as generating or replaying a message.

There are different kinds of messages for different kinds of data and that's all (mostly) defined in the SDK. 

The idea behind the utility, is that it reads messages from multiple fit files, and replays the messages into a single fit file. There is some complication in that not all messages need to be repeated. What I would call the "header" and "footer" messages need to be curated to construct a valid dive fit file. I also learned that Garmin Dive is more picky on what's in the fit file than Garmin Connect.

Information also needs to be curated as well, such as picking the right coordinates for the start of the dive, and the end of the dive, min-max values etc. In addition to that, the summary data such as average depth, bottom time etc need to be recalculated. It's interesting to note the record messages (which record real time data) aren't capturing at consistent intervals, so you can't just take an average of the data-set for an accurate average.

All of this is based on deconstructing a single file first, and learning the structure of the data. Have to give a shoutout to https://www.fitfileviewer.com/ to peek into the files, and to see what I was spitting out initially.

If you want to give it a another crack, I'm more than happy to help.

**Comment by hellozee** [comment]
> All of this is based on deconstructing a single file first, and learning the structure of the data. Have to give a shoutout to https://www.fitfileviewer.com/ to peek into the files, and to see what I was spitting out initially.

Damn, that website is a gem, now things are pretty clear that I can at least write for my personal use, to automate the whole thing.

Thanks a ton.
